#!/usr/bin/env node
/**
 * shipkit setup — generate apps/web/.env.local from a preset (ShipFast TTP)
 *
 * Usage:
 *   pnpm setup -- --preset=demo
 *   pnpm setup -- --preset=portable-pg
 *   pnpm setup -- --preset=supabase-full
 *   pnpm setup -- --preset=portable-pg --force
 */
import { writeFileSync, existsSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const args = process.argv.slice(2);
const force = args.includes("--force");
const presetArg = args.find((a) => a.startsWith("--preset="));
const preset = presetArg?.split("=")[1] || "demo";

const dest = resolve(root, "apps/web/.env.local");

if (existsSync(dest) && !force) {
  console.error(`
✗ apps/web/.env.local already exists.
  Re-run with --force to overwrite, or edit the file manually.
`);
  process.exit(1);
}

const secret = randomBytes(24).toString("hex"); // 48 chars

const templates = {
  demo: `# Shipkit demo — UI only (no real auth)
# Generated by: pnpm setup -- --preset=demo

NEXT_PUBLIC_APP_URL=http://localhost:3000
NEXT_PUBLIC_SHIPKIT_MODE=demo
`,

  "portable-pg": `# Shipkit portable-pg (Better Auth + Docker Postgres)
# Generated by: pnpm setup -- --preset=portable-pg
# 1) pnpm db:up && pnpm db:migrate
# 2) pnpm doctor && pnpm dev

NEXT_PUBLIC_APP_URL=http://localhost:3000
NEXT_PUBLIC_SHIPKIT_MODE=better-auth
DATABASE_URL=postgresql://shipkit:shipkit@localhost:5432/shipkit
BETTER_AUTH_SECRET=${secret}
BETTER_AUTH_URL=http://localhost:3000
AUTH_ADAPTER=better-auth
`,

  "supabase-full": `# Shipkit supabase-full
# Generated by: pnpm setup -- --preset=supabase-full
# Paste real URL + anon key, run SQL in dashboard, then pnpm dev

NEXT_PUBLIC_APP_URL=http://localhost:3000
NEXT_PUBLIC_SHIPKIT_MODE=supabase
NEXT_PUBLIC_SUPABASE_URL=https://YOUR_PROJECT.supabase.co
NEXT_PUBLIC_SUPABASE_ANON_KEY=your-anon-key-here
AUTH_ADAPTER=supabase
`,
};

if (!templates[preset]) {
  console.error(`Unknown preset: ${preset}
Valid: demo | portable-pg | supabase-full
`);
  process.exit(1);
}

writeFileSync(dest, templates[preset], "utf8");

console.log(`
✦ shipkit setup

  Preset : ${preset}
  Wrote  : apps/web/.env.local
`);

if (preset === "portable-pg") {
  console.log(`  Next:
    pnpm db:up
    pnpm db:migrate
    pnpm doctor
    pnpm dev
`);
} else if (preset === "supabase-full") {
  console.log(`  Next:
    # paste real Supabase URL + anon key into apps/web/.env.local
    pnpm doctor
    pnpm dev
`);
} else {
  console.log(`  Next:
    pnpm doctor
    pnpm dev          # demo UI only
`);
}
